### ISSUE TITLE
Support meta data

### ISSUE THREAD

**Issue by oeway** [VeliovGroup/meteor-python-files#2]
Currently, meta data of the file is not uploaded. Need to find a way to extract meta data in python and convert it into json format.

**Comment by dr-dimitru** [comment]
Take a look on [`fixJSONParse`](https://github.com/VeliovGroup/Meteor-Files/blob/master/files.coffee#L391) and [`fixJSONStringify`](https://github.com/VeliovGroup/Meteor-Files/blob/master/files.coffee#L410), if you're planning to send _Date_ Object in meta

**Comment by oeway** [comment]
For now, I just leave meta as an argument for the user.
