### ISSUE TITLE
How to upload to https://files.veliov.com

### ISSUE THREAD

**Issue by oeway** [VeliovGroup/meteor-python-files#3]
Would be great if we can have an example to upload files to https://files.veliov.com.

**Comment by dr-dimitru** [comment]
I need a little more explanation.
I believe you know how to upload files via `HTTP` all code of this demo is open.
For `DDP` you can try to use `wss://wssfiles.veliov.com`

Do you need this for testing? Because I can not guarantee `files.veliov.com` will always has latest driver version.

**Comment by oeway** [comment]
Never mind it's not necessary, just wondering if it possible to upload to files.veliov.com .

**Comment by dr-dimitru** [comment]
Okay. yes, it's possible
