### ISSUE TITLE
Trouble running example

### ISSUE THREAD

**Issue by dhamaniasad** [VeliovGroup/meteor-python-files#5]
When I try to run the example from the README, I get this error in Python:

``` python
file size: 6486, chunk size: 163840, chunk count: 1
start upload
sending: 1/1
'bool' object has no attribute '__getitem__'
```

This is what is printed to the log in demo-simplest-upload:

```
I20160830-03:23:42.895(5.5)? [FilesCollection] [find({}, undefined)]
I20160830-03:23:42.917(5.5)? [FilesCollection] [File Start Method] test.png - a9fc98cf-dcb2-427a-9621-f80b7cef890f
I20160830-03:23:42.919(5.5)? [FilesCollection] [Upload] [Start Method] Got #-1/1 chunks, dst: test.png
I20160830-03:23:42.923(5.5)? [FilesCollection] [Abort Method]: a9fc98cf-dcb2-427a-9621-f80b7cef890f - assets/app/uploads/Images/a9fc98cf-dcb2-427a-9621-f80b7cef890f.png
I20160830-03:23:42.925(5.5)? [FilesCollection] [remove({"_id":"a9fc98cf-dcb2-427a-9621-f80b7cef890f"})]
I20160830-03:23:42.928(5.5)? [FilesCollection] [unlink(a9fc98cf-dcb2-427a-9621-f80b7cef890f, undefined)]
I20160830-03:23:42.929(5.5)? [FilesCollection] [_preCollectionCursor.observeChanges] [removed]: a9fc98cf-dcb2-427a-9621-f80b7cef890f
```

For Python, I am at commit `0473fe2482505df7a42c71363ec642ca4709160f`. For demo-simplest-upload, commit `ab05e46d28504663d9c893505847fec739dee9a8`.

**Comment by oeway** [comment]
Could you post all the error trackback?

**Comment by dhamaniasad** [comment]
What I posted above is all that was printed to the console. If I comment out

``` python
while not uploader.finished:
    time.sleep(0.1)
```

then I do not see the error, but it stops after uploading the first chunk.

**Comment by oeway** [comment]
Sorry, that's not enough to track the issue. 

Try to track which line triggered that error,  and please report your python version (2.7 is the version I used to test). 

And also, try to install https://pypi.python.org/pypi/magic,  or pass `fileType="image/png"` to Uploader, see if these make any difference.

**Comment by dhamaniasad** [comment]
Found the source. `metaResult` is a boolean, and there's this line of code: `metaResult['uploadRoute']`. 

![](https://puu.sh/qT9V1/810b219a6f.png) 

Python version is `2.7.11`. Tried magic too. So it looks like `_upload_start_callback(self, error, metaResult)` is being passed a `Bool` by the python-meteor client. If you are not able to reproduce this issue, I can try some more digging around.

I will also try running this on a Linux machine and report back soon.

**Comment by dr-dimitru** [comment]
Hi all,

Isn't file id `a9fc98cf-dcb2-427a-9621-f80b7cef890f` look weird?
Have you used `namingFunction`?

**Comment by dhamaniasad** [comment]
@dr-dimitru Just using the standard demo application without any modifications.

**Comment by dhamaniasad** [comment]
UPDATE: Ran on Ubuntu 16.04, Python 2.7.12, still same error. Steps for reproduction:

```
git clone https://github.com/VeliovGroup/Meteor-Files.git
cd Meteor-Files/demo-simplest-upload
meteor
```

New terminal tab:

```
git clone https://github.com/VeliovGroup/meteor-python-files.git
cd meteor-python-files
pip install python-meteor requests
```

Created a file `test.py`, copied the code from the example in the README, and `python test.py`. 
Python output: 

``` python
file size: 72952, chunk size: 163840, chunk count: 1
start upload
sending: 1/1
'bool' object has no attribute '__getitem__'
```

**Comment by oeway** [comment]
@dr-dimitru a9fc98cf-dcb2-427a-9621-f80b7cef890f is a random name generated by a python uuid generator, I used that as a fileId.

@dhamaniasad   I think I know why you get this error, that's because when you launch `meteor` in demo-simplest-upload, meteor will take ostri-files library from meteor repository rather than compile it from Meteor-Files folder. It uses a out-dated version of Meteor-Files without "returnMeta" support, so that's why you get that error. What I did is to setup a meteor local pacakge, you could have a look at here: http://stackoverflow.com/questions/18328000/installing-a-local-package-on-meteor

@dr-dimitru when do you plan to update the meteor hosted version?

**Comment by dhamaniasad** [comment]
I used a local package at the current `HEAD` of Meteor-Files, and it works using the DDP transport. HTTP transport gives me this error:

``` python
file size: 253558, chunk size: 163840, chunk count: 3
start upload
callback
sending: 1/3
Header value 0 must be of type str or bytes, not <type 'int'>
```

I'll just stick with DDP for the time being. Thanks for all the help!

**Comment by dr-dimitru** [comment]
@oeway I'll update all demo apps within next version release

**Comment by dhamaniasad** [comment]
@dr-dimitru Do you have any plans to add support for direct HTTP uploads? meteor-file-collection supports uploading like this:

``` bash
curl -X POST 'http://127.0.0.1:3000/gridfs/fs/38a14c8fef2d6cef53c70792' \
     -F 'file=@"lolcat.gif";type=image/gif' \
     -H 'X-Auth-Token: 3pl5vbN_ZbKDJ1ko5JteO3ZSTrnQIl5g6fd8XW0U4NQ'
```

I just wrote an [article](http://www.asad.pw/2016/08/30/file-uploads-with-meteor.html) about file uploads with Meteor, and lack of the above was my only problem with Meteor-File. Thanks for all the amazing work!

**Comment by dr-dimitru** [comment]
@dhamaniasad 
This is actually possible now. Need to update docs, see [#206](https://github.com/VeliovGroup/Meteor-Files/issues/206)

**Comment by dhamaniasad** [comment]
@dr-dimitru That was quick! I'll try to work out the details and add the docs later today, will keep you posted.

**Comment by dr-dimitru** [comment]
@dhamaniasad thank you

> That was quick!

You just caught me awake

**Comment by dhamaniasad** [comment]
@dr-dimitru So I'm having some trouble. I'm trying to use requests to begin with, and this is my code:

``` python
import requests
import uuid
import os
import time
import base64

fileId = str(uuid.uuid4())
headers = {"x-start": "1",
"x-mtok": "4zpQ4eAaxCDTAj4LD"}

body = {"fileId": fileId, "chunkSize": "6486","fileLength": "1"}
body["file"] = {"name": "test.png", "type":"image/png", "size": "6486", "meta": {}}

r = requests.post("http://localhost:3000/cdn/storage/Images/__upload", headers=headers, json=body)


time.sleep(0.2)
headers = {"x-mtok": "4zpQ4eAaxCDTAj4LD", "x-fileid": fileId, "x-chunkid": "1", "content-type": "text/plain"}
with open("test.png", "rb") as image_file:
    data = base64.b64encode(image_file.read())
r = requests.post("http://localhost:3000/cdn/storage/Images/__upload", headers=headers, data=data)

time.sleep(0.2)
headers = {"x-mtok": "4zpQ4eAaxCDTAj4LD", "x-fileid": fileId, "x-eof": "1", "content-type": "text/plain"}
r = requests.post("http://localhost:3000/cdn/storage/Images/__upload", headers=headers)
```

I run this, this is logged in the demo-simplest-upload:

```
I20160830-18:43:21.389(5.5)? [FilesCollection] [File Start HTTP] test.png - b3d30b8a-3127-4a60-b0b5-2c45737c9cbb
I20160830-18:43:21.390(5.5)? [FilesCollection] [Upload] [Start Method] Got #-1/1 chunks, dst: test.png
I20160830-18:43:21.614(5.5)? [FilesCollection] [Upload] [HTTP] Got #1/1 chunks, dst: test.png
I20160830-18:43:21.833(5.5)? [FilesCollection] [Upload] [HTTP] Got #-1/1 chunks, dst: test.png
```

The Python code gets stuck waiting for a response, and no new file seems to get added.

**Comment by dr-dimitru** [comment]
1. Try this code with no auth header `x-mtok`
2. Have you tried `time.sleep(2)` (_to make sure_)
3. Have you checked what `base64.b64encode(image_file.read())` returns?
4. Try `chunkSize = actualSize - 128`, and **note** size should be in bytes, not length of base64 string
5. I've just released v1.7.2 there was various related fixes, could you please update?

> The Python code gets stuck waiting for a response, and no new file seems to get added.

Are you sure it's stuck? Note "first byte" and "EOF" returns `204: empty response`, may Python be confused of this?

**Comment by dr-dimitru** [comment]
@oeway demo apps is updated

**Comment by dhamaniasad** [comment]
Tried all of that, still get the same issue. `base64.b64encode(image_file.read())` output is [here](https://gist.github.com/dhamaniasad/77e6765864f8c5f374fe413e9ad9fbc1).

**Comment by dr-dimitru** [comment]
DDP upload is works for you?

**Comment by dhamaniasad** [comment]
Yes, DDP upload works for me, HTTP doesn't.

**Comment by dr-dimitru** [comment]
Is debug logs changed somehow after our latest updates/changes?

**Comment by dhamaniasad** [comment]
I'll try running this again and report back. It might take some hours as it's night time here.

**Comment by dhamaniasad** [comment]
@dr-dimitru I've switched to file-collection for the time being, sorry I couldn't be of more help. I had time constraints but you are doing amazing work with Meteor-Files and I am really thankful for all your hard work :)!

**Comment by dr-dimitru** [comment]
@dhamaniasad hope you will use it on your next project

**Comment by dhamaniasad** [comment]
@dr-dimitru I intend to! If you could make plain HTTP uploads easier, something like

```
curl -X POST 'http://127.0.0.1:3000/gridfs/fs/38a14c8fef2d6cef53c70792' \
     -F 'file=@"lolcat.gif";type=image/gif' \
     -H 'X-Auth-Token: 3pl5vbN_ZbKDJ1ko5JteO3ZSTrnQIl5g6fd8XW0U4NQ'
```

from file-collection, then I would never look anywhere else :).

**Comment by dr-dimitru** [comment]
I'll think how to make it possible
