### ISSUE TITLE
Get the downloadable url of a file

### ISSUE THREAD

**Issue by oeway** [VeliovGroup/meteor-python-files#6]
I want to get the url for downloading a file, but in python we can't actually call the function formatFleURL:
https://github.com/VeliovGroup/Meteor-Files/blob/master/files.coffee#L2344

Is is possible to get it directly from the file object?

**Comment by dr-dimitru** [comment]
Yes, 

here is format: `{_downloadRoute}/{_collectionName}/{_id}/{version}/#{_id}#{ext}`
But it's different for public and protected collections

**Comment by oeway** [comment]
Can I find root url somewhere?

**Comment by dr-dimitru** [comment]
env.var?

**Comment by oeway** [comment]
> env.var?

Perhaps not, python code is running on the client.
One way is to make a meteor method, or extract from the websocket url.

**Comment by dr-dimitru** [comment]
> extract from the web socket url

Sounds right, unless `Meteor.absoluteURL` is implemented in meteor-python
see: https://docs.meteor.com/api/core.html#Meteor-absoluteUrl

**Comment by oeway** [comment]
Thanks, will try implement it.
